In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [ ]:
#importing the dataset

df = pd.read_csv("/content/Bank_Modelling.csv")
x = df.iloc[:,3:13].values
y = df.iloc[:,13].values
print(x)
print(y)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]
[1 0 1 ... 1 1 0]


In [ ]:
#Encoding categorial data

from sklearn.preprocessing import LabelEncoder, OneHotEncoder

labelencoder_X_1 = LabelEncoder()
x[:,1] = labelencoder_X_1.fit_transform(x[:,1])

x

array([[619, 0, 'Female', ..., 1, 1, 101348.88],
       [608, 2, 'Female', ..., 0, 1, 112542.58],
       [502, 0, 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 0, 'Female', ..., 0, 1, 42085.58],
       [772, 1, 'Male', ..., 1, 0, 92888.52],
       [792, 0, 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [ ]:
labelencoder_X_2 = LabelEncoder()
x[:,2] = labelencoder_X_2.fit_transform(x[:,2])

x

array([[619, 0, 0, ..., 1, 1, 101348.88],
       [608, 2, 0, ..., 0, 1, 112542.58],
       [502, 0, 0, ..., 1, 0, 113931.57],
       ...,
       [709, 0, 0, ..., 0, 1, 42085.58],
       [772, 1, 1, ..., 1, 0, 92888.52],
       [792, 0, 0, ..., 1, 0, 38190.78]], dtype=object)

In [ ]:
from sklearn.compose import ColumnTransformer

ct = ColumnTransformer([("Country", OneHotEncoder(),[1])], remainder = "passthrough")
x = ct.fit_transform(x)

x.astype(int)
x

array([[1.0, 0.0, 0.0, ..., 1, 1, 101348.88],
       [0.0, 0.0, 1.0, ..., 0, 1, 112542.58],
       [1.0, 0.0, 0.0, ..., 1, 0, 113931.57],
       ...,
       [1.0, 0.0, 0.0, ..., 0, 1, 42085.58],
       [0.0, 1.0, 0.0, ..., 1, 0, 92888.52],
       [1.0, 0.0, 0.0, ..., 1, 0, 38190.78]], dtype=object)

In [ ]:
x = x[:, 1:]
x

array([[0.0, 0.0, 619, ..., 1, 1, 101348.88],
       [0.0, 1.0, 608, ..., 0, 1, 112542.58],
       [0.0, 0.0, 502, ..., 1, 0, 113931.57],
       ...,
       [0.0, 0.0, 709, ..., 0, 1, 42085.58],
       [1.0, 0.0, 772, ..., 1, 0, 92888.52],
       [0.0, 0.0, 792, ..., 1, 0, 38190.78]], dtype=object)

In [ ]:
from pandas.core.common import random_state
#splitting the daatset into the training set and test set

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(x, y,test_size = 0.2, random_state = 0)

X_train

array([[0.0, 1.0, 667, ..., 1, 0, 163830.64],
       [1.0, 0.0, 427, ..., 1, 1, 57098.0],
       [0.0, 0.0, 535, ..., 1, 0, 185630.76],
       ...,
       [0.0, 0.0, 738, ..., 1, 0, 181429.87],
       [0.0, 1.0, 590, ..., 1, 1, 148750.16],
       [1.0, 0.0, 623, ..., 1, 0, 118855.26]], dtype=object)

In [ ]:
X_test

array([[1.0, 0.0, 597, ..., 1, 1, 192852.67],
       [0.0, 0.0, 523, ..., 1, 0, 128702.1],
       [0.0, 1.0, 706, ..., 1, 1, 75732.25],
       ...,
       [0.0, 1.0, 578, ..., 1, 0, 141533.19],
       [1.0, 0.0, 650, ..., 1, 1, 11276.48],
       [1.0, 0.0, 573, ..., 1, 0, 192950.6]], dtype=object)

In [ ]:
y_train

array([0, 0, 0, ..., 0, 0, 1])

In [ ]:
y_test

array([0, 1, 0, ..., 0, 0, 0])

In [ ]:
#Feature Scaling

from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

X_train
X_test

array([[ 1.75486502, -0.57369368, -0.55204276, ...,  0.64259497,
         0.9687384 ,  1.61085707],
       [-0.5698444 , -0.57369368, -1.31490297, ...,  0.64259497,
        -1.03227043,  0.49587037],
       [-0.5698444 ,  1.74309049,  0.57162971, ...,  0.64259497,
         0.9687384 , -0.42478674],
       ...,
       [-0.5698444 ,  1.74309049, -0.74791227, ...,  0.64259497,
        -1.03227043,  0.71888467],
       [ 1.75486502, -0.57369368, -0.00566991, ...,  0.64259497,
         0.9687384 , -1.54507805],
       [ 1.75486502, -0.57369368, -0.79945688, ...,  0.64259497,
        -1.03227043,  1.61255917]])

In [ ]:
#now it's make the ANN

import keras
from keras.models import Sequential  #connection are sequential
from keras.layers import Dense   #saying ann is fully connected

In [ ]:
#Initialising the ANN

classifier = Sequential()

In [ ]:
#Adding the input layer and the first hidden layer

classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 11))

In [ ]:
#adding the 2nd hidden

classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))

In [ ]:
#adding the output layer

classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))

In [ ]:
#compiling the ANN
#compile - goin to the method gradient-descend algo..to reduce the error 
#optimizer - adam algo - 
#if categorical tn = loss = 'categotical_crossentropy'
classifier.compile(optimizer = 'adam',loss = 'binary_crossentropy', metrics = ['accuracy'])

In [ ]:
#Fitting the ANN to the Training set
#fit - to train the model 
classifier.fit(X_train, y_train, batch_size = 10, epochs = 100)

Epoch 1/100
800/800 [==============================] - 2s 2ms/step - loss: 0.4870 - accuracy: 0.7950
Epoch 2/100
800/800 [==============================] - 1s 2ms/step - loss: 0.4278 - accuracy: 0.7960
Epoch 3/100
800/800 [==============================] - 1s 2ms/step - loss: 0.4225 - accuracy: 0.7960
Epoch 4/100
800/800 [==============================] - 1s 2ms/step - loss: 0.4190 - accuracy: 0.8217
Epoch 5/100
800/800 [==============================] - 1s 2ms/step - loss: 0.4162 - accuracy: 0.8271
Epoch 6/100
800/800 [==============================] - 2s 2ms/step - loss: 0.4146 - accuracy: 0.8282
Epoch 7/100
800/800 [==============================] - 1s 2ms/step - loss: 0.4124 - accuracy: 0.8300
Epoch 8/100
800/800 [==============================] - 1s 2ms/step - loss: 0.4113 - accuracy: 0.8324
Epoch 9/100
800/800 [==============================] - 1s 2ms/step - loss: 0.4105 - accuracy: 0.8322
Epoch 10/100
800/800 [==============================] - 1s 2ms/step - loss: 0.4092 - accura

In [ ]:
#part - 3 - Making the predictions and evaluating the model

#predicting the test set results

y_pred = classifier.predict(X_test)

y_pred

array([[0.19735393],
       [0.32284257],
       [0.19317833],
       ...,
       [0.18068859],
       [0.15382549],
       [0.13058716]], dtype=float32)

In [ ]:
y_pred = (y_pred > 0.5)

y_pred

array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [False]])

In [ ]:
#Making the confusion matrix

from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred)

In [ ]:
cm

array([[1542,   53],
       [ 261,  144]])

In [ ]:
sum = (1542 + 144)/ 2000

In [ ]:
sum

0.843