In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
#importing the dataset

df = pd.read_csv("/content/Bank_Modelling.csv")
x = df.iloc[:,3:13].values
y = df.iloc[:,13].values
print(x)
print(y)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]
[1 0 1 ... 1 1 0]


In [3]:
#Encoding categorial data

from sklearn.preprocessing import LabelEncoder, OneHotEncoder

labelencoder_X_1 = LabelEncoder()
x[:,1] = labelencoder_X_1.fit_transform(x[:,1])

x

array([[619, 0, 'Female', ..., 1, 1, 101348.88],
       [608, 2, 'Female', ..., 0, 1, 112542.58],
       [502, 0, 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 0, 'Female', ..., 0, 1, 42085.58],
       [772, 1, 'Male', ..., 1, 0, 92888.52],
       [792, 0, 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [4]:
labelencoder_X_2 = LabelEncoder()
x[:,2] = labelencoder_X_2.fit_transform(x[:,2])

x

array([[619, 0, 0, ..., 1, 1, 101348.88],
       [608, 2, 0, ..., 0, 1, 112542.58],
       [502, 0, 0, ..., 1, 0, 113931.57],
       ...,
       [709, 0, 0, ..., 0, 1, 42085.58],
       [772, 1, 1, ..., 1, 0, 92888.52],
       [792, 0, 0, ..., 1, 0, 38190.78]], dtype=object)

In [5]:
from sklearn.compose import ColumnTransformer

ct = ColumnTransformer([("Country", OneHotEncoder(),[1])], remainder = "passthrough")
x = ct.fit_transform(x)

x.astype(int)
x

array([[1.0, 0.0, 0.0, ..., 1, 1, 101348.88],
       [0.0, 0.0, 1.0, ..., 0, 1, 112542.58],
       [1.0, 0.0, 0.0, ..., 1, 0, 113931.57],
       ...,
       [1.0, 0.0, 0.0, ..., 0, 1, 42085.58],
       [0.0, 1.0, 0.0, ..., 1, 0, 92888.52],
       [1.0, 0.0, 0.0, ..., 1, 0, 38190.78]], dtype=object)

In [6]:
x = x[:, 1:]
x

array([[0.0, 0.0, 619, ..., 1, 1, 101348.88],
       [0.0, 1.0, 608, ..., 0, 1, 112542.58],
       [0.0, 0.0, 502, ..., 1, 0, 113931.57],
       ...,
       [0.0, 0.0, 709, ..., 0, 1, 42085.58],
       [1.0, 0.0, 772, ..., 1, 0, 92888.52],
       [0.0, 0.0, 792, ..., 1, 0, 38190.78]], dtype=object)

In [7]:
from pandas.core.common import random_state
#splitting the daatset into the training set and test set

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(x, y,test_size = 0.2, random_state = 0)

X_train

array([[0.0, 1.0, 667, ..., 1, 0, 163830.64],
       [1.0, 0.0, 427, ..., 1, 1, 57098.0],
       [0.0, 0.0, 535, ..., 1, 0, 185630.76],
       ...,
       [0.0, 0.0, 738, ..., 1, 0, 181429.87],
       [0.0, 1.0, 590, ..., 1, 1, 148750.16],
       [1.0, 0.0, 623, ..., 1, 0, 118855.26]], dtype=object)

In [8]:
X_test

array([[1.0, 0.0, 597, ..., 1, 1, 192852.67],
       [0.0, 0.0, 523, ..., 1, 0, 128702.1],
       [0.0, 1.0, 706, ..., 1, 1, 75732.25],
       ...,
       [0.0, 1.0, 578, ..., 1, 0, 141533.19],
       [1.0, 0.0, 650, ..., 1, 1, 11276.48],
       [1.0, 0.0, 573, ..., 1, 0, 192950.6]], dtype=object)

In [9]:
y_train

array([0, 0, 0, ..., 0, 0, 1])

In [10]:
y_test

array([0, 1, 0, ..., 0, 0, 0])

In [11]:
#Feature Scaling

from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

X_train
X_test

array([[ 1.75486502, -0.57369368, -0.55204276, ...,  0.64259497,
         0.9687384 ,  1.61085707],
       [-0.5698444 , -0.57369368, -1.31490297, ...,  0.64259497,
        -1.03227043,  0.49587037],
       [-0.5698444 ,  1.74309049,  0.57162971, ...,  0.64259497,
         0.9687384 , -0.42478674],
       ...,
       [-0.5698444 ,  1.74309049, -0.74791227, ...,  0.64259497,
        -1.03227043,  0.71888467],
       [ 1.75486502, -0.57369368, -0.00566991, ...,  0.64259497,
         0.9687384 , -1.54507805],
       [ 1.75486502, -0.57369368, -0.79945688, ...,  0.64259497,
        -1.03227043,  1.61255917]])

**Artificial Neural Network**

In [18]:
#import the keras libraries and packages
import keras
from keras.models import Sequential #importing sequential model
from keras.layers import Dense #fully connected layer structure


In [19]:
#Initialising the ANN
classifier = Sequential()#classifier is ANNA which is sequential

In [20]:
#Adding the input layer and the first hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 11)) #give a dense layer, some small number is initialized to the weight, 11 units are given to 6 hidden unit 11 units 1 initializer 11+1= 12/2
#relu rectitfies  0 and 1

In [22]:
#adding the second hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))#one more hidden layer

In [21]:
#Adding output layer
classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))#output will be sigmoidal

In [24]:
#compiling the ANN
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy']) #optimizer is the algo used to reduce the error here we use adam algo, error we used to calculate here is binary_crossentropy, based on accuracy 

In [25]:
#fitting the ANN to the training set
classifier.fit(X_train, y_train, batch_size = 10, epochs = 100 )

Epoch 1/100
800/800 [==============================] - 3s 2ms/step - loss: 0.9588 - accuracy: 0.0000e+00
Epoch 2/100
800/800 [==============================] - 2s 2ms/step - loss: 0.9049 - accuracy: 0.0050
Epoch 3/100
800/800 [==============================] - 2s 2ms/step - loss: 0.8845 - accuracy: 1.2500e-04
Epoch 4/100
800/800 [==============================] - 2s 2ms/step - loss: 0.8737 - accuracy: 0.0000e+00
Epoch 5/100
800/800 [==============================] - 2s 2ms/step - loss: 0.8645 - accuracy: 0.0000e+00
Epoch 6/100
800/800 [==============================] - 2s 2ms/step - loss: 0.8558 - accuracy: 1.2500e-04
Epoch 7/100
800/800 [==============================] - 2s 2ms/step - loss: 0.8467 - accuracy: 0.0886
Epoch 8/100
800/800 [==============================] - 2s 2ms/step - loss: 0.8379 - accuracy: 0.0185
Epoch 9/100
800/800 [==============================] - 2s 2ms/step - loss: 0.8319 - accuracy: 0.0204
Epoch 10/100
800/800 [==============================] - 2s 2ms/step - l

In [26]:
#part 3 -Making prediction and evaluating the model
#predicting the test results
y_pred = classifier.predict(X_test)
y_pred

array([[0.        , 0.3585974 , 0.3585974 , 0.3585974 , 0.3585974 ,
        0.3585974 ],
       [0.        , 0.3589159 , 0.3589159 , 0.3589159 , 0.3589159 ,
        0.3589159 ],
       [0.        , 0.18753561, 0.18753561, 0.18753561, 0.18753561,
        0.18753561],
       ...,
       [0.        , 0.25278285, 0.25278285, 0.25278285, 0.25278285,
        0.25278285],
       [0.        , 0.22626776, 0.22626776, 0.22626776, 0.22626776,
        0.22626776],
       [0.        , 0.1980484 , 0.1980484 , 0.1980484 , 0.1980484 ,
        0.1980484 ]], dtype=float32)

In [27]:
y_pred = (y_pred > 0.5)#ypred greater then 0.5 true else false
y_pred

array([[False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       ...,
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False]])

In [31]:
#making the confusion matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

ValueError: ignored

In [ ]:
#improve accuracy of model
#use another data set for same code
